springbootservice:
  hostname: spring-microservice
  build: springboot/
  ports:
    - "8100:8081"

#mononancynet:
#  hostname: net-nancy-mono-service
#  build: SimpleNancy/
#  ports:
#    - "8100:8081"

#HINT 1: MAYBE YOU SHOULD SET UP A NODESERVICE?
#HINT 2: MAYBE YOU SHOULD TAKE A LOOK AT LINK?
#HINT 3: DO YOU NEED A MONGO?

